### PR TITLE
Misc HTML doc generation changes

### PR DESCRIPTION
**Pull request by kianmeng**
List of changes:
- Indent code example
- Use common source url
- Include readme and set as default page
- Badges and more badges!
- Add link to Hanzi and Pinyin
- Add extra line to each iex code example

Screenshot.

image

### CODE REVIEW

**Comment by mathsaey** [comment]
Sorry for taking a while to reply to this. For some reason github didn't notify me about your PR.

Your changes look good to me, with the exception of wrapping all the comments to 80 characters long. When using Elixir, I wrap my lines to 98 characters (as that is the default `line_length` for [`format_string/2`](https://hexdocs.pm/elixir/Code.html#format_string!/2), which is used by `mix format`). I think it would be best if the comments and the code were consistent in this regard.

**Comment by kianmeng** [comment]
> Sorry for taking a while to reply to this. For some reason github didn't notify me about your PR.

Is okay. No biggie.

> Your changes look good to me, with the exception of wrapping all the comments to 80 characters long. When using Elixir, I wrap my lines to 98 characters (as that is the default `line_length` for [`format_string/2`](https://hexdocs.pm/elixir/Code.html#format_string!/2), which is used by `mix format`). I think it would be best if the comments and the code were consistent in this regard.

Noted. I've reverted these changes but still keep the extra empty for each iex command in code example because it really help with readability.

**Comment by mathsaey** [comment]
> Noted. I've reverted these changes but still keep the extra empty for each iex command in code example because it really help with readability.

Agreed. I wanted to complain about this at first (it leads to unnecessary emtpy doctests), but the elixir docs seem to do the same. I'll merge this, thanks!

**Comment by kianmeng** [comment]
> Your changes look good to me, with the exception of wrapping all the comments to 80 characters long. When using Elixir, I wrap my lines to 98 characters (as that is the default `line_length` for [`format_string/2`](https://hexdocs.pm/elixir/Code.html#format_string!/2), which is used by `mix format`). I think it would be best if the comments and the code were consistent in this regard.

@mathsaey 
Should we explore something like https://editorconfig.org/ so that future contributors will follow the maintainer style and convention?

**Comment by mathsaey** [comment]
That sounds like a good idea. I'd propose something like this:

```
root = true

[*.{ex,exs}]

indent_size = 2
indent_style = space

max_line_length = 98

end_of_line = lf
insert_final_newline = false
trim_trailing_whitespace = true
```

**Pull request merged**
